### ISSUE TITLE
Eliminate or hash inline scripts

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.com#111]
Currently, the only place we have inline scripts is my (currently not used) modal, which uses Alpine, and in the CMS for previews, and the print button on TOS page. We could move them out of the partial and into scripts, but that sacrifices portability. Alternatively, we can [hash](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script) the scripts, as in #109. But we should discuss. 

- [ ] search modal
- [x] CMS 
- [x] TOS print dialogue (moved to scripts)

**Comment by regisphilibert** [comment]
I don't think hashing CMS inline scripts would be too much problematic.

**Comment by budparr** [comment]
Yeah, once #108 is set, we can make the decision on a case-by-case basis. I had left the modal script in the partial just because I saw it as a potential module, but it doesn't have to be there.
