### ISSUE TITLE
Add Fathom Goal test

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/thenewdynamic.com#113]
Add a test goal to discover the feature and how it can help us.

**Comment by regisphilibert** [comment]
@budparr I tried the above here: https://github.com/theNewDynamic/thenewdynamic.com/blob/86ca46302e37aa7f64a6cd21e2079faf406f99d8/layouts/partials/lang-switch.html#L15

But I get this error:
```
Refused to connect to 'https://img3.usefathom.com/?gcode=HUH3RMSE&gval=0' because it violates the following Content Security Policy directive: "connect-src 'self' https://cdn.usefathom.com".

beacon @ VM324 script.js:1
trackGoal @ VM324 script.js:1
eval @ VM331:3
(anonymous) @ VM318 main.b07ac33c039285b4de64.js:1
evaluateCommandExpression @ VM318 main.b07ac33c039285b4de64.js:1
_ @ VM318 main.b07ac33c039285b4de64.js:1
l @ VM318 main.b07ac33c039285b4de64.js:1
``` 

Not sure how to address. Will circle back.

**Comment by budparr** [comment]
hmm. We don't allow inline scripts 🙊 Is that `@click` Alpine?

**Comment by regisphilibert** [comment]
It is.

**Comment by budparr** [comment]
I think we could add the script to our scripts output 

`assets/js/analytics.js`
with 
```
document.getElementById('about-us-link').addEventListener('click', () => {
    fathom.trackGoal('B5PGZD9N', 0);
});
```
and just make sure that we load our script after Fathom. that's from: https://usefathom.com/support/goals

**Comment by budparr** [comment]
I think that would be nice and organized anyway. Will it work for you?

**Comment by regisphilibert** [comment]
So I switched to adding the test to our module sandbox: https://tnd-modules.netlify.app/fathom/ had have been clicking... but cannot see any stats on the Goal yet...

Will circle back tomorrow.

**Comment by budparr** [comment]
Closing. Will revisit later as the need arises.
