### ISSUE TITLE
Improve cache busting on Hugo JSON

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.com#120]
I created a simple JSON shortcode to pull in API data

/content/en/info/privacy-policy.md
```
{{< json "https://www.iubenda.com/api/privacy-policy/xxxxxx?20200704" >}}
```

and 
/layouts/shortcodes/json.html
```
{{ with .Get 0 }}
    {{ $data := getJSON . }}
    <div class="max-w-4xl my-32">
        {{ $data.content | safeHTML }}
    </div>
{{ end }}
```

Note in the markdown document I'm using a query string (I put in the date, but could be anything) so that if I change the content from the API, Hugo updates the content pulled into the page. It does not update otherwise. 

**We certainly want the data cached so it's not pulling in on each build**, but using a query string means that each time the content is updated from the API, the query string needs to be adjusted, which could be cumbersome and error prone. 

This issue is meant to explore if there is a better method for breaking the cache.

**Comment by regisphilibert** [comment]
### Cache Setting
We could set our getJSON cache [setting](https://gohugo.io/getting-started/configuration/#configure-file-caches) to 1 day. This means the API would be pinged once a day (or less if build frequency is less than a day, probably here on our own corporate website). 
## Upside
We never have to worry about bust caching
## Downside
We don't have a proper way to immediately busting the cache. So whenever the API is updated we should wait for a day for it be updated on the site.

### Append global site "bust caching value" on the getJSON URL.
We could either use the page's last updated time as a hash, but this still means we'll have to find a way to update the page whenever the API needs to refresh. Potentially having to "update" every page concerned.
Or, we could use a `site.Params` which could take an internal version reference. (version_1_1) or symver etc... 

## Upside
We can bust the cache anytime we want.
## Downside
We need to intervene everytime the API is updated but only on the site settings.

@budparr once we decide which way to go, I will adivse against having a globlal json shortocde as the content the repsonse is not likely to be the same (expecting a `$data.content` is risky.
But I will wrap this solution in a `hugo-module-tnd-iubenda` as we're likely to use it on several projects.

**Comment by budparr** [comment]
These things might only be updated once or twice a year, so the second option is best. 

Yes, I agree. I knew the solution was short term, I just wanted to get my various policies. 

Related to your last note: https://github.com/theNewDynamic/thenewdynamic.com/issues/121

**Comment by budparr** [comment]
Also, note if you're going to make a module, there's CSS involved. This is the sort of thing that could change from site to site, but not too terribly likely. It's a total pain to get this stuff to look decent:

https://github.com/theNewDynamic/thenewdynamic.com/blob/main/assets/css/iubenda.css

**Comment by regisphilibert** [comment]
I'd rather leave the styling to module user's responsability. Making those easily adjustable is always tricky.
For us, as those shortcodes and therefore the printed h1/h2 etc.. are printed under the page's content blocks, shouldn't they fall under our `.rich-text` styling?

**Comment by budparr** [comment]
we should chat about this
