### ISSUE TITLE
Code Pricing Tables

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.com#148]
I put in the copy for the pricing tables. I think the structure I used in the prototype is sufficient. Now we need to get them consistent and more easily editable:

Content here:
https://github.com/theNewDynamic/thenewdynamic.com/blob/main/content/en/agile-pricing-plans.md

/agile-pricing-plans/

The current prototype lives here (based on [this](https://tailwindui.com/components/marketing/sections/pricing#component-56cbd4f191ac0d54e5a5c0287481d5b9)):
https://github.com/theNewDynamic/thenewdynamic.com/blob/main/layouts/partials/plans.html

The top section (with copy: All Plans include 400gb) can be left for now.

Below that there are three sections. The top-most section is correct (the price box is to the right on large screens). We need to put the content from the prototype in blocks on the content page and code the sections to consume the content.

The only issue that's not correct on the prototype is that the checked items (green check mark) aren't aligning.

@regisphilibert is the way forward on this clear?

**Comment by regisphilibert** [comment]
I'll review and let you know.
