### ISSUE TITLE
Add Reporting address to CSP

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.com#211]
Please add reporting to our CSP: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#enabling_reporting

use this email: https://thenewdynamic.report-uri.com/r/d/csp/enforce

**Comment by regisphilibert** [comment]
just did
![Capture d’écran, le 2022-05-06 à 11 10 19](https://user-images.githubusercontent.com/1480503/167161325-c8c485d7-80ed-4eeb-b278-b4c3d1923ac2.png)
!
