### ISSUE TITLE
Add mobile menu

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.com#30]
As discussed. I have the essentials of this mocked up in Figma (screenshots attached)/

- [x] type is `text-sm` ( = 14px). 
- [x] Padding is not reflected well in the mockup, but each menu item should have generous padding to create adequate touch target space (i.e. use spacing generally from mockup, but they should be padding, not margins). 
- [x] dropdown should use similar animation as language switcher
- [x] if possible, expanded dropdown should overlay content below it, not push it down.
- [x] Visible menu items (non-drop-down state) should be chosen in config, not just the two first items (so we can display critical mobile items up top, like contact).
- [x] "more v" should change to "close v" upon opening.

I may want to tweak once we have a prototype, but I think the above covers the spec.

![Screenshot 2020-05-21 12.34.25.jpg](https://zube.io/files/the-new-dynamic/88b39090b3d5fc78ce358420db732c72-screenshot-2020-05-21-12-34-25.jpg)

open state:
![Screenshot 2020-05-21 12.34.31.jpg](https://zube.io/files/the-new-dynamic/dc2fb9d915ee91d8a0afc8178cb05cde-screenshot-2020-05-21-12-34-31.jpg)

**Comment by regisphilibert** [comment]
> dropdown should use similar animation as language switcher

The problem I have here is that we cannot simply hide and show with Alpine. We have to manipulate classes with Alpine, because this element (second part of the menu) needs to be hidden/shown on mobile, but systematically visible on desktop.

**Comment by budparr** [comment]
I did something like that on tnd.org I'll have a look.

**Comment by budparr** [comment]
Not sure if this is helpful to you. I didn't use animations on it (only discovered the Alpine/TW animation goodness recently) https://github.com/theNewDynamic/thenewdynamic.org/blob/master/layouts/partials/search/refinement-lists.html#L6

**Comment by regisphilibert** [comment]
Ok! I think we're now complying with every requests :)
