### ISSUE TITLE
Improve themes and gradient

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.com#61]
@regisphilibert I've run roughshod over your theme CSS, and I've changed the gradient. Ideally, I'd like to change them more. Can we/you(!) find me way I can just load the gradient parameters into the Tailwind config and to change them globally?

**Comment by budparr** [comment]
actually, I see that we can do something like `linear-gradient(blue, green);` but I think we need something with more breakpoints.

**Comment by budparr** [comment]
This is what I have now:
```
	background-color: linear-gradient(
		52deg,
		#410252 0%,
		#63004c 16%,
		#810045 33%,
		#9f003e 50%,
		#bc0435 66%,
		#da0c2b 83%,
		#f8141d 100%
	);
```

**Comment by budparr** [comment]
Just noting, that with the gradient, I broke the map. We'll need to fix that, even though we'll soon be adding to or changing that hero.

**Comment by budparr** [comment]
Sorry for the inundation of comments! 

Note: https://github.com/benface/tailwindcss-gradients

which I typically prefer to use (plugins, that is)

**Comment by regisphilibert** [comment]
No worry about the comments :).  With your finding of the plugin do you still need me?

**Comment by budparr** [comment]
No. I think the plugin will work well. I put in the colors once and plugin spit out the code below, which makes it usable in a variety of scenarios and it can easily tweaked:
```

.bg-gradient-t-primary {
  background-image: linear-gradient(to top, #410252 0%, #63004c, 16%, #810045 33%, #9f003e 50%, #bc0435 66%, #da0c2b 83%, #f8141d 100%);
}

.bg-gradient-tr-primary {
  background-image: linear-gradient(to top right, #410252 0%, #63004c, 16%, #810045 33%, #9f003e 50%, #bc0435 66%, #da0c2b 83%, #f8141d 100%);
}

.bg-gradient-r-primary {
  background-image: linear-gradient(to right, #410252 0%, #63004c, 16%, #810045 33%, #9f003e 50%, #bc0435 66%, #da0c2b 83%, #f8141d 100%);
}

.bg-gradient-br-primary {
  background-image: linear-gradient(to bottom right, #410252 0%, #63004c, 16%, #810045 33%, #9f003e 50%, #bc0435 66%, #da0c2b 83%, #f8141d 100%);
}

.bg-gradient-b-primary {
  background-image: linear-gradient(#410252 0%, #63004c, 16%, #810045 33%, #9f003e 50%, #bc0435 66%, #da0c2b 83%, #f8141d 100%);
}

.bg-gradient-bl-primary {
  background-image: linear-gradient(to bottom left, #410252 0%, #63004c, 16%, #810045 33%, #9f003e 50%, #bc0435 66%, #da0c2b 83%, #f8141d 100%);
}
```
