### ISSUE TITLE
Check the contact form

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/thenewdynamic.com#75]

**Comment by budparr** [comment]
This is the final issue for our soft launch

**Comment by regisphilibert** [comment]
Yes. Another pb is we don't have any easy solution for tranlsation. I suppose we'll have two forms for now.

**Comment by regisphilibert** [comment]
The form works great. What email should we send the notifications to though? We need to verify it through the formspree platform.

**Comment by budparr** [comment]
welcome@thenewdynamic.com

**Comment by regisphilibert** [comment]
All good
