### ISSUE TITLE
Style Syntax Highlighting

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/thenewdynamic.com#87]
Syntax Highlighting is in place with now only 2 languages basically styled.

@budparr I created a branch for you and I to play with [85-highlight-custom](https://github.com/theNewDynamic/thenewdynamic.com/tree/85-highlight-custom) and its https://github.com/theNewDynamic/thenewdynamic.com/pull/88 PR.

the articles in using code blocks are drafted but I setup netlify to publish drafts on deploy previews. 

https://deploy-preview-88--thenewdynamic.netlify.app/article/hugo-modules/
https://deploy-preview-88--thenewdynamic.netlify.app/article/hugo-context/

We should only bother ourselves with the css variables at the top of this file: https://github.com/theNewDynamic/thenewdynamic.com/blob/77a0d0ec941a5e939c19806e675aafea06572a7e/assets/css/highlight.css#L7-L63

We can chat anytime.

**Comment by regisphilibert** [comment]
@budparr slight issue is we have to run `nn deploy` with the articles in question "undrafted" so `hugo_stats.json` prints their classes on the final css used by Netlify. 

We could put something in place, as this might surface again (having to run some drafted page and take into account their classes for PurceCSS). But in the mean time, I just undraft the piece before running the deploy script). We could also keep them undrafted on this PR.

**Comment by budparr** [comment]
got it, thank you
