### ISSUE TITLE
Add post-article promo block

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.com#91]
After every article we should include some promotional language about our firm and possibly a CTA (newsletter, etc)

**Comment by regisphilibert** [comment]
I'll cook up something temporary based on what we already have elsewhere and we can review copy together. What do you think @budparr ?

**Comment by budparr** [comment]
sounds good

**Comment by regisphilibert** [comment]
@budparr as you can see I made something real quick. You can adjust or close. The content of the promotion is set through FM. (Cascade on the post's landing for now but could be custom to any post)

**Comment by budparr** [comment]
Can we have a different one based on the content? That copy is good for dev stuff, not so much for people who don't know what Jamstack is (and we don't care if our clients know what Jamstack is, only what it does). Otherwise, maybe we can make something a bit more agnostic.

**Comment by regisphilibert** [comment]
Let's draft copies and I'll adjust.

**Comment by budparr** [comment]
Oh, I think that's good enough. Just to be able to override is fine. Looks great!
