### ISSUE TITLE
Add social shares to articles

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.com#93]
I'd like these to be subtle. 

The word "share:" should be present on the right-side (right hand side of the max-width setting) of the top bar (the bar that only shows on scroll) with three gray-scale icons, Twitter, Linkedin, email. (fuck facebook)

![Screenshot 2020-06-18 12 40 48](https://user-images.githubusercontent.com/115347/85048305-2477da80-b161-11ea-8d1e-7f41cc8f05cf.jpg)

**Comment by regisphilibert** [comment]
I think I'll take care of this today. I might use the opportunity to revise the script of this sticky element as it's currently conflicting with our headers.

**Comment by regisphilibert** [comment]
@budparr Did you just write `fuck` on a public repo 😄  ?

**Comment by regisphilibert** [comment]
@budparr what kind of email subject/body are we talking about? Any idea?
