### ISSUE TITLE
Experiment Netlify Large File

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/thenewdynamic.com#96]

**Comment by budparr** [comment]
Looks like the set of transforms is significantly smaller than imgix's https://docs.netlify.com/large-media/transform-images/

**Comment by regisphilibert** [comment]
Oh sh....t. Indeed! Hugo has way more than that...

**Comment by budparr** [comment]
note, if we "try" it on a repo: "in case you don’t like it, we have to help you turn it off, and we may not see your request quickly to do so."

so might be better for a less consequential repo

**Comment by regisphilibert** [comment]
Well, the fact that it only has 2 transformations turns this thing solely about the hosting of large files.

On this one aspect alone, do we still want to proceed with the test drive?

**Comment by budparr** [comment]
No, I don't think so.
